### ISSUE TITLE
Switch the UID for Eagle and Peacock and redo the code names

### ISSUE THREAD

**Issue by cmiller8** [buds-lab/building-data-genome-project-2#12]
I had the UID/Code names switched for Eagle and Peacock! Therefore we need to redo the unique id code names. I think we should take the opportunity to reorder the code name to: "AnimalName_SimplifiedSpaceUse_HumanName" -- I think this is a good idea so when people sort the UID, then it groups the buildings in more logical groups. Also, I think some of the Space Uses can be simplified so there is no "/" in the names

**Comment by cmiller8** [comment]
Also rename `wolve` to `wolf`

I think this is the best thing to do first while we double-check all the units

**Comment by ponybiam** [comment]
On it! This will be made on the[ `
ashrae-great-energy-predictor-3-internal-data-prep`](https://github.com/buds-lab/ashrae-great-energy-predictor-3-internal-data-prep) repository, where the first conversion was developed. I will re-organize the _Building Data Genome 2.0_ folder and split the notebooks in smaller ones. Once the data sets are fully transformed and corrected, I'll bring them to this repository.
- [ ] Rename `Wolve` to `Wolf`
- [ ]  Switch `Eagle` and `Peacock`
- [ ] Simplify `primaryspaceusage` (limit to 10 chars and remove special chars)
- [ ] Rename buildings as _AnimalName_SimplifiedSpaceUse_HumanName_
- [ ] Update documentation

**Comment by ponybiam** [comment]
This task was completed on the  [ashrae-great-energy-predictor-3-internal-data-prep](https://github.com/buds-lab/ashrae-great-energy-predictor-3-internal-data-prep/tree/BDG-conversion) (`BDG-conversion` branch).

What was accomplished:
- `Eagle` and `Peacock` were switched
- `Wolve` was renamed to `Wolf`
- Only `cleaned` data was converted (in the old version `merged` data was also converted, but if they won't be used it makes not sense having them in the repository)
- All buildings were renamed with the pattern: _AnimalSiteName_SimplifiedUsage_UniqueHumanName_
- Weather data set was corrected to local time (instead of UTC)
- Not units were converted (this will be done as part of the cleaning process in BDG2 repository)
- 2016-2017 meters data will be copied to BDG2 repository, and will be the `raw` meters data (this is like and extended version of Kaggle competition data set, the data is the same but with more buildings and metadata features).
